import type { TenantCountryRoutingConfig } from "./types.js";

const argentinaJurisdictions: TenantCountryRoutingConfig["jurisdictions"] = {
  nacion: {
    type: "nacion",
    label: "Nacion",
    pluralLabel: "Naciones",
    description: "Country-level public site and governance surface.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  provincia: {
    type: "provincia",
    label: "Provincia",
    pluralLabel: "Provincias",
    description: "First-order provincial jurisdiction.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  "ciudad-autonoma": {
    type: "ciudad-autonoma",
    label: "Ciudad autonoma",
    pluralLabel: "Ciudades autonomas",
    description: "Autonomous city jurisdiction, used by CABA.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  municipio: {
    type: "municipio",
    label: "Municipio",
    pluralLabel: "Municipios",
    description: "Local government surface. Buenos Aires municipalities are historically called partidos.",
    routeSegmentStrategy: "postal-slug",
    requiresPostalCode: true,
  },
  partido: {
    type: "partido",
    label: "Partido",
    pluralLabel: "Partidos",
    description: "Buenos Aires Province second-order jurisdiction wording.",
    routeSegmentStrategy: "postal-slug",
    requiresPostalCode: true,
  },
  departamento: {
    type: "departamento",
    label: "Departamento",
    pluralLabel: "Departamentos",
    description: "Second-order jurisdiction outside Buenos Aires Province and CABA.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  comuna: {
    type: "comuna",
    label: "Comuna",
    pluralLabel: "Comunas",
    description: "CABA comuna or province-specific commune surface.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  barrio: {
    type: "barrio",
    label: "Barrio",
    pluralLabel: "Barrios",
    description: "Neighborhood-level public site surface.",
    routeSegmentStrategy: "postal-slug",
    requiresPostalCode: true,
  },
};

export const ARGENTINA_TENANT_ROUTING_CONFIG: TenantCountryRoutingConfig = {
  countryCode: "ar",
  countryName: "Argentina",
  defaultJurisdictionType: "municipio",
  pathTemplate: "/{countryCode}/{jurisdictionType}/{routeSegment}",
  workerNameTemplate: "ciutatis-{countryCode}-{jurisdictionType}-{routeSegment}",
  jurisdictionAliases: {
    argentina: "nacion",
    country: "nacion",
    nation: "nacion",
    state: "provincia",
    province: "provincia",
    caba: "ciudad-autonoma",
    city: "municipio",
    ciudad: "municipio",
    county: "partido",
    neighborhood: "barrio",
    neighbourhood: "barrio",
  },
  jurisdictions: argentinaJurisdictions,
  launchTenants: [
    {
      name: "Tandil City",
      municipalityName: "Municipio de Tandil",
      countryCode: "ar",
      jurisdictionType: "municipio",
      postalCode: "7000",
      citySlug: "tandil",
      shortCode: "7000",
      parentSubdivisionCode: "buenos-aires",
      parentSubdivisionName: "Provincia de Buenos Aires",
      pathPrefix: "/ar/municipio/7000-tandil",
      dispatcherKey: "ar/municipio/7000-tandil",
    },
  ],
};
