import type { TenantCountryRoutingConfig } from "./types.js";

const usJurisdictions: TenantCountryRoutingConfig["jurisdictions"] = {
  nacion: {
    type: "nacion",
    label: "Nation",
    pluralLabel: "Nations",
    description: "Country-level public site and governance surface.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  provincia: {
    type: "provincia",
    label: "State",
    pluralLabel: "States",
    description: "First-order state jurisdiction.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  "ciudad-autonoma": {
    type: "ciudad-autonoma",
    label: "Federal District",
    pluralLabel: "Federal Districts",
    description: "Federal district jurisdiction, used by Washington D.C.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  municipio: {
    type: "municipio",
    label: "City",
    pluralLabel: "Cities",
    description: "Local city government surface.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  partido: {
    type: "partido",
    label: "County",
    pluralLabel: "Counties",
    description: "County-level jurisdiction.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  departamento: {
    type: "departamento",
    label: "Borough",
    pluralLabel: "Boroughs",
    description: "Borough or township jurisdiction.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  comuna: {
    type: "comuna",
    label: "Township",
    pluralLabel: "Townships",
    description: "Township or commune surface.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
  barrio: {
    type: "barrio",
    label: "Neighborhood",
    pluralLabel: "Neighborhoods",
    description: "Neighborhood-level public site surface.",
    routeSegmentStrategy: "slug",
    requiresPostalCode: false,
  },
};

export const US_TENANT_ROUTING_CONFIG: TenantCountryRoutingConfig = {
  countryCode: "us",
  countryName: "United States",
  defaultJurisdictionType: "municipio",
  pathTemplate: "/{countryCode}/{jurisdictionType}/{routeSegment}",
  workerNameTemplate: "ciutatis-{countryCode}-{jurisdictionType}-{routeSegment}",
  jurisdictionAliases: {
    usa: "nacion",
    us: "nacion",
    nation: "nacion",
    country: "nacion",
    state: "provincia",
    province: "provincia",
    county: "partido",
    parish: "partido",
    city: "municipio",
    town: "municipio",
    village: "municipio",
    borough: "departamento",
    township: "comuna",
    neighborhood: "barrio",
    neighbourhood: "barrio",
  },
  jurisdictions: usJurisdictions,
  launchTenants: [],
};
