import type { CreateConfigValues } from "@paperclipai/adapter-utils";
import { DEFAULT_CLOUDFLARE_WORKERS_AI_MODEL } from "@ciutatis/adapter-cloudflare-workers-ai";

export const defaultCreateValues: CreateConfigValues = {
  adapterType: "cloudflare_workers_ai",
  cwd: "",
  instructionsFilePath: "",
  promptTemplate: "",
  model: DEFAULT_CLOUDFLARE_WORKERS_AI_MODEL,
  thinkingEffort: "",
  chrome: false,
  dangerouslySkipPermissions: true,
  search: false,
  dangerouslyBypassSandbox: false,
  command: "",
  args: "",
  extraArgs: "",
  envVars: "",
  envBindings: {},
  url: "",
  bootstrapPrompt: "",
  payloadTemplateJson: "",
  workspaceStrategyType: "project_primary",
  workspaceBaseRef: "",
  workspaceBranchTemplate: "",
  worktreeParentDir: "",
  runtimeServicesJson: "",
  maxTurnsPerRun: 300,
  heartbeatEnabled: false,
  intervalSec: 300,
};
