export const API_PREFIX = "/api";

export const API = {
  health: `${API_PREFIX}/health`,
  contact: `${API_PREFIX}/contact`,
  institutions: `${API_PREFIX}/companies`,
  companies: `${API_PREFIX}/companies`,
  tenantInstances: `${API_PREFIX}/instance/settings/tenants`,
  agents: `${API_PREFIX}/agents`,
  projects: `${API_PREFIX}/projects`,
  requests: `${API_PREFIX}/issues`,
  issues: `${API_PREFIX}/issues`,
  objectives: `${API_PREFIX}/goals`,
  goals: `${API_PREFIX}/goals`,
  approvals: `${API_PREFIX}/approvals`,
  secrets: `${API_PREFIX}/secrets`,
  costs: `${API_PREFIX}/costs`,
  activity: `${API_PREFIX}/activity`,
  dashboard: `${API_PREFIX}/dashboard`,
  sidebarBadges: `${API_PREFIX}/sidebar-badges`,
  invites: `${API_PREFIX}/invites`,
  joinRequests: `${API_PREFIX}/join-requests`,
  members: `${API_PREFIX}/members`,
  admin: `${API_PREFIX}/admin`,
} as const;
