# Cloudflare Pages - Ciutatis public site (Next.js)
name = "ciutatis-ui"
compatibility_date = "2025-01-01"

account_id = "b9f5ebc6c05975fab56f056782461b77"

[build]
command = "npm run build"
directory = "dist"

[env.production]
name = "ciutatis-ui"

[env.staging]
name = "ciutatis-ui-staging"
