# Cloudflare Pages - Ciutatis Public Landing
name = "ciutatis-landing"
compatibility_date = "2025-01-01"

account_id = "b9f5ebc6c05975fab56f056782461b77"

[build]
command = "npm run build"
directory = "dist"

[env.production]
name = "ciutatis-landing"

[env.staging]
name = "ciutatis-landing-staging"
