import { index, pgTable, text, timestamp, uuid, uniqueIndex } from "drizzle-orm/pg-core";
import type { TenantBootstrapStatus, TenantInstanceStatus, TenantRoutingMode } from "@paperclipai/shared";

export const tenantInstances = pgTable(
  "tenant_instances",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    municipalityName: text("municipality_name").notNull(),
    countryCode: text("country_code").notNull(),
    jurisdictionType: text("jurisdiction_type").notNull().default("municipio"),
    postalCode: text("postal_code"),
    citySlug: text("city_slug").notNull(),
    shortCode: text("short_code").notNull(),
    parentSubdivisionCode: text("parent_subdivision_code"),
    parentSubdivisionName: text("parent_subdivision_name"),
    routingMode: text("routing_mode").$type<TenantRoutingMode>().notNull().default("path"),
    status: text("status").$type<TenantInstanceStatus>().notNull().default("draft"),
    pathPrefix: text("path_prefix").notNull(),
    dispatcherKey: text("dispatcher_key").notNull(),
    hostname: text("hostname"),
    workerName: text("worker_name").notNull(),
    dispatchScriptName: text("dispatch_script_name"),
    tenantD1DatabaseId: text("tenant_d1_database_id"),
    tenantD1DatabaseName: text("tenant_d1_database_name"),
    tenantKvNamespaceId: text("tenant_kv_namespace_id"),
    tenantKvNamespaceTitle: text("tenant_kv_namespace_title"),
    tenantR2BucketName: text("tenant_r2_bucket_name"),
    bootstrapStatus: text("bootstrap_status").$type<TenantBootstrapStatus>().notNull().default("pending"),
    lastDeploymentStartedAt: timestamp("last_deployment_started_at", { withTimezone: true }),
    lastDeploymentFinishedAt: timestamp("last_deployment_finished_at", { withTimezone: true }),
    lastDeploymentError: text("last_deployment_error"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    pathPrefixIdx: uniqueIndex("tenant_instances_path_prefix_idx").on(table.pathPrefix),
    dispatcherKeyIdx: uniqueIndex("tenant_instances_dispatcher_key_idx").on(table.dispatcherKey),
    hostnameIdx: uniqueIndex("tenant_instances_hostname_idx").on(table.hostname),
    workerNameIdx: uniqueIndex("tenant_instances_worker_name_idx").on(table.workerName),
    jurisdictionRouteIdx: index("tenant_instances_jurisdiction_route_idx").on(
      table.countryCode,
      table.jurisdictionType,
      table.postalCode,
      table.citySlug,
    ),
    statusIdx: index("tenant_instances_status_idx").on(table.status),
  }),
);
